pipeline {
    agent {
        docker {
            image 'node:8-alpine' 
            args '-p 2000:2000' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'yarn install'
		sh 'yarn build' 
            }
        }
    }
}
