pipeline {
	agent {
		docker {
			image 'node:8-alpine' 
			args '-p 2000:2000' 
		}
	}
	stages {
		stage('Build') { 
			steps {
				sh 'npm install -g yarn'
				sh 'yarn install --production'
				sh 'yarn build' 
				sshagent(credentials: ['lightsail']) {
					sh 'ssh -o StrictHostKeyChecking=no -l centos foobar.digitalruiz.com  sleep 10 ; /usr/bin/nohup /usr/bin/http-server -p 3000 /opt/node_server/client/ &' 
				}
			}
		}
	}
}
